### ISSUE TITLE
Appending as the only insertion method for arrays is too limiting

### ISSUE THREAD

**Issue by anEXPer** [cppforlife/go-patch#6]
We currently use an append to the `instance_groups` array in our bosh manifest to add an optional instance group. However, we discovered that we need this instance group to come up not-last. Since bosh deploys instance groups, broadly, in order, appending isn't an appropriate insertion method for jobs that need to come up before other jobs.

We'd be happy to insert before or after a given name, or even at an index number of the array.

**Comment by drnic** [comment]
My requirement scenario for being able to insert into an array was to add `consul_agent` job onto an instance_group such as `etcd` for SSL support. I assumed `/0` was prepend but that replaces the first time.

If we need another single character for prepend, then since `-` is append, perhaps `+` for prepend.

```
- type: replace
  path: /instance_groups/name=etcd/jobs/+
  value:
```

**Comment by geofffranks** [comment]
+1

**Comment by cppforlife** [comment]
resolved in https://github.com/cppforlife/go-patch/issues/11
